### ISSUE TITLE
object allocated on the heap may not be aligned 16

### ISSUE THREAD

**Issue by Daivuk** [xoorath/xo-math#7]
Need to find a solution to this problem.

When I have a class with members like Matrix, lets say:
```
class Entity
{
    Matrix4x4 transform;
};
```
If I allocate Entity with new operator, I get this warning.
In DX maths, the vectors are _loaded_, then _stored_ back after the operation.
It's slower, but it makes usage a lot easier.

**Comment by xoorath** [comment]
Yeah, been thinking about solutions to that.

One option: rename current types such as `Vector3` to `Vector3Reg` and provide 1) A class that wraps these  and loads with the standard name `Vector3` and 2) simd alignment macro so the user can still use `Vector3Reg` and have the benefit of not loading/storing values whenever used.

In the second case you would do something like:

```
// The following is a performance critical class:
XO_SIMD_ALIGN
class Entity {
    XO_ALIGNED_NEW_DELETE();
    Matrix4x4Reg transform;
    // other simd aligned types....

   // other types that don't need to be aligned
};

// The following is a non performance critical class:
class GameplayCode {
    Matrix4x4 transform;
};
```

Maybe this is overkill? I'd be interested to hear your thoughts.
